desc "Create all nfl teams"
task :create_all_teams => :environment do
	Team.create(abbr: "ARI", teamname: "arizonacardinals", city: "Phoenix", estd: DateTime.parse("01/01/1920 00:00:00"), conf: "NFC", div: "NCW", website: "http://www.azcardinals.com/")
	Team.create(abbr: "DAL", teamname: "dallascowboys", city: "Dallas", estd: DateTime.parse("01/01/1960 00:00:00"), conf: "NFC", div: "NCE", website: "http://www.dallascowboys.com")
	Team.create(abbr: "NE", teamname: "newenglandpatriots", city: "Boston", estd: DateTime.parse("01/01/1960 00:00:00"), conf: "AFC", div: "ACE", website: "http://www.patriots.com")
	Team.create(abbr: "DEN", teamname: "denverbroncos", city: "Denver", estd: DateTime.parse("01/01/1960 00:00:00"), conf: "AFC", div: "ACW", website: "http://www.denverbroncos.com")
	Team.create(abbr: "DET", teamname: "detroitlions", city: "Detroit", estd: DateTime.parse("01/01/1930 00:00:00"), conf: "NFC", div: "NCN", website: "http://www.detroitlions.com")
	Team.create(abbr: "GB", teamname: "greenbaypackers", city: "Green Bay", estd: DateTime.parse("01/01/1921 00:00:00"), conf: "NFC", div: "NCN", website: "http://www.packers.com")
	Team.create(abbr: "KC", teamname: "kansascitychiefs", city: "Kansas City", estd: DateTime.parse("01/01/1960 00:00:00"), conf: "AFC", div: "ACW", website: "http://www.kcchiefs.com")
	Team.create(abbr: "PHI", teamname: "philadelphiaeagles", city: "Philadelphia", estd: DateTime.parse("01/01/1933 00:00:00"), conf: "NFC", div: "NCE", website: "http://www.philadelphiaeagles.com")
	Team.create(abbr: "CIN", teamname: "cincinnatibengals", city: "Cincinnati", estd: DateTime.parse("01/01/1968 00:00:00"), conf: "AFC", div: "ACN", website: "http://www.bengals.com")
	Team.create(abbr: "PIT", teamname: "pittsburghsteelers", city: "Pittsburgh", estd: DateTime.parse("01/01/1933 00:00:00"), conf: "AFC", div: "ACN", website: "http://www.steelers.com")
	Team.create(abbr: "BAL", teamname: "baltimoreravens", city: "Baltimore", estd: DateTime.parse("01/01/1996 00:00:00"), conf: "AFC", div: "ACN", website: "http://www.baltimoreravens.com")
	Team.create(abbr: "CLE", teamname: "clevelandbrowns", city: "Cleveland", estd: DateTime.parse("01/01/1946 00:00:00"), conf: "AFC", div: "ACN", website: "http://www.clevelandbrowns.com")
	Team.create(abbr: "IND", teamname: "indianapoliscolts", city: "Indianapolis", estd: DateTime.parse("01/01/1944 00:00:00"), conf: "AFC", div: "ACS", website: "http://www.colts.com")
	Team.create(abbr: "MIA", teamname: "miamidolphins", city: "Miami", estd: DateTime.parse("01/01/1966 00:00:00"), conf: "AFC", div: "ACE", website: "http://www.miamidolphins.com")
	Team.create(abbr: "SD", teamname: "sandiegochargers", city: "San Diego", estd: DateTime.parse("01/01/1960 00:00:00"), conf: "AFC", div: "ACW", website: "http://www.chargers.com")
	Team.create(abbr: "SF", teamname: "sanfrancisco49ers", city: "San Francisco", estd: DateTime.parse("01/01/1946 00:00:00"), conf: "NFC", div: "NCW", website: "http://www.49ers.com")
	Team.create(abbr: "SEA", teamname: "seattleseahawks", city: "Seattle", estd: DateTime.parse("01/01/1976 00:00:00"), conf: "NFC", div: "NCW", website: "http://www.seahawks.com")
	Team.create(abbr: "BUF", teamname: "buffalobills", city: "Buffalo", estd: DateTime.parse("01/01/1960 00:00:00"), conf: "AFC", div: "ACE", website: "http://www.buffalobills.com")
	Team.create(abbr: "HOU", teamname: "houstontexans", city: "Houston", estd: DateTime.parse("01/01/2002 00:00:00"), conf: "AFC", div: "ACS", website: "http://www.houstontexans.com")
	Team.create(abbr: "ATL", teamname: "atlantahawks", city: "Atlanta", estd: DateTime.parse("01/01/1966 00:00:00"), conf: "NFC", div: "NCS", website: "http://www.atlantafalcons.com")
	Team.create(abbr: "CHI", teamname: "chicagobulls", city: "Chicago", estd: DateTime.parse("01/01/1920 00:00:00"), conf: "NFC", div: "NCN", website: "http://www.chicagobears.com")
	Team.create(abbr: "MIN", teamname: "minnesotavikings", city: "Minneapolis", estd: DateTime.parse("01/01/1961 00:00:00"), conf: "NFC", div: "NCN", website: "http://www.vikings.com")
	Team.create(abbr: "NO", teamname: "neworleanssaints", city: "New Orleans", estd: DateTime.parse("01/01/1967 00:00:00"), conf: "NFC", div: "NCS", website: "http://www.neworleanssaints.com")
	Team.create(abbr: "STL", teamname: "stlouisrams", city: "St Louis", estd: DateTime.parse("01/01/1937 00:00:00"), conf: "NFC", div: "NCW", website: "http://www.stlouisrams.com")
	Team.create(abbr: "CAR", teamname: "carolinapanthers", city: "Charlotte", estd: DateTime.parse("01/01/1995 00:00:00"), conf: "NFC", div: "NCS", website: "http://www.panthers.com")
	Team.create(abbr: "NYG", teamname: "newyorkgiants", city: "New York", estd: DateTime.parse("01/01/1925 00:00:00"), conf: "NFC", div: "NCE", website: "http://www.giants.com")
	Team.create(abbr: "WAS", teamname: "washingtonredskins", city: "Washington", estd: DateTime.parse("01/01/1932 00:00:00"), conf: "NFC", div: "NCE", website: "http://www.redskins.com")
	Team.create(abbr: "NYJ", teamname: "newyorkjets", city: "New York", estd: DateTime.parse("01/01/1960 00:00:00"), conf: "AFC", div: "ACE", website: "http://www.newyorkjets.com")
	Team.create(abbr: "TB", teamname: "tampabaybuccaneers", city: "Tampa Bay", estd: DateTime.parse("01/01/1976 00:00:00"), conf: "NFC", div: "NCS", website: "http://www.buccaneers.com")
	Team.create(abbr: "TEN", teamname: "tennesseetitans", city: "Nashville", estd: DateTime.parse("01/01/1960 00:00:00"), conf: "AFC", div: "ACS", website: "http://www.titansonline.com")
	Team.create(abbr: "JAC", teamname: "jacksonvillejaguars", city: "Jacksonville", estd: DateTime.parse("01/01/1995 00:00:00"), conf: "AFC", div: "ACS", website: "http://www.jaguars.com")
	Team.create(abbr: "OAK", teamname: "oaklandraiders", city: "Oakland", estd: DateTime.parse("01/01/1960 00:00:00"), conf: "AFC", div: "ACW", website: "http://www.raiders.com")
	Team.create(abbr: "AFC", teamname: "afc", city: "American Conference", estd: DateTime.parse("01/01/1960 00:00:00"), conf: "AFC", div: "AllStar", website: "")
	Team.create(abbr: "NFC", teamname: "nfc", city: "National Conference", estd: DateTime.parse("01/01/1960 00:00:00"), conf: "NFC", div: "AllStar", website: "")
	Team.create(abbr: "SAN", teamname: "deionsanders", city: "NFL", estd: DateTime.parse("01/01/1960 00:00:00"), conf: "AFC", div: "AllStar", website: "")
	Team.create(abbr: "RIC", teamname: "rayrice", city: "NFL", estd: DateTime.parse("01/01/1960 00:00:00"), conf: "NFC", div: "AllStar", website: "")
end
